# version: "3.8"   # (You can skip "version" now as it is deprecated)

services:
  fastapi:
    build:
      context: .
      dockerfile: src/deployment/Dockerfile
    container_name: twitter-sentiment-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./data/processed:/app/data/processed
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus:latest
    container_name: twitter-sentiment-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: twitter-sentiment-node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:latest
    container_name: twitter-sentiment-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  pushgateway:
    image: prom/pushgateway
    container_name: twitter-sentiment-pushgateway
    ports:
      - "9091:9091"

volumes:
  grafana-storage:
